#pragma once
#include "CCAntiCheat.h"
#include <iostream>
#include <fstream>
#include <Windows.h>

using namespace std;

enum ChatColors
{
	CHATCOLOR_BLACK,
	CHATCOLOR_DARKRED,
	CHATCOLOR_DARKGREEN,
	CHATCOLOR_GOLD,
	CHATCOLOR_DARKGREY,
	CHATCOLOR_GREEN,
	CHARCOLOR_RED,
	CHATCOLOR_YELLOW,
	CHATCOLOR_DARKBLUE,
	CHATCOLOR_DARKAQUA,
	CHATCOLOR_DARKPURPLE,
	CHATCOLOR_GRAY,
	CHARCOLOR_BLUE,
	CHATCOLOR_AQUA,
	CHATCOLOR_LIGHTPURPLE,
	CHATCOLOR_WHITE
};

enum ChatCosmetics
{
	CHATCOSMETICS_RANDOMLETTER,
	CHATCOSMETICS_STRIKETROUGH,
	CHATCOSMETICS_ITALIC,
	CHATCOSMETICS_BOLD,
	CHATCOSMETICS_UNDERLINE
};